--
-- EXPLAIN redaction — leak-detection harness and fixture schema
--
-- This file is task T01 of the auto-explain redaction plan.  It deliberately
-- contains NO product code and tests NO redaction behavior: at this point
-- EXPLAIN (REDACT) does not exist yet.
--
-- Its entire purpose is to build the leak detector and prove that it works,
-- by asserting that the detector FINDS the fixture identifiers in today's
-- ordinary, unredacted EXPLAIN output.  A detector that reported "clean"
-- because it was looking in the wrong place, or because its pattern never
-- matched, would silently pass every later task in the plan.  So the positive
-- control comes first, before there is anything to redact.
--
-- Every fixture object carries the marker prefix "zsec_".  The requirements
-- doc originally proposed a bare "z" prefix on the grounds that nothing in
-- core EXPLAIN output starts with z; that is not true -- "timestamp with time
-- zone" contains "zone", which a /z[a-z_]+/ detector reports as a leak.  The
-- four-character marker cannot collide with any English or SQL word appearing
-- in plan output, so the detector needs no word-boundary anchoring and has no
-- false positives.

CREATE SCHEMA zsec_ns;
SET search_path = zsec_ns, public;

CREATE COLLATION zsec_coll (locale = 'C');
CREATE TYPE zsec_composite AS (zsec_fld_ssn text, zsec_fld_name text);
CREATE TYPE zsec_enum AS ENUM ('zsec_val_a', 'zsec_val_b');
CREATE DOMAIN zsec_domain AS text CHECK (VALUE <> '');

CREATE TABLE zsec_customers (
    zsec_id     int GENERATED BY DEFAULT AS IDENTITY,
    zsec_ssn    text,
    zsec_bal    numeric,
    zsec_when   timestamptz,
    zsec_comp   zsec_composite,
    zsec_kind   zsec_enum
);
-- Unique, so the ON CONFLICT fixture below has an arbiter index to name.
CREATE UNIQUE INDEX zsec_idx_ssn ON zsec_customers (zsec_ssn);
-- Needed to make the planner choose a MinMax-aggregate plan, which is one of
-- the shapes that produces a childless Result node (see the FR-92 probe).
CREATE INDEX zsec_idx_bal ON zsec_customers (zsec_bal);

CREATE TABLE zsec_orders (zsec_id int, zsec_amt numeric);

-- A CHECK constraint the planner can use to prove a scan empty, which yields a
-- childless Result node (see the FR-92 probe).
CREATE TABLE zsec_excluded (zsec_k int CHECK (zsec_k > 0));

-- Declared plpgsql on purpose: an inlinable SQL function would be folded away
-- by the planner and the FuncExpr (and therefore the function name and the
-- named-argument label) would never reach the plan tree.
CREATE FUNCTION zsec_func(zsec_arg text) RETURNS boolean
    LANGUAGE plpgsql VOLATILE AS $$ BEGIN RETURN true; END $$;

-- Marked DATA, not just marked schema.
--
-- The detector greps for the marker, which catches leaked *identifiers*.  It is
-- blind to leaked *values* -- a real SSN in a Filter clause is not an identifier
-- and matches nothing.  Rather than build a classifier that recognises
-- arbitrary sensitive data, the values are made self-identifying too: every
-- stored value carries the same marker, so a leaked value is exactly as
-- detectable as a leaked name, by the same one-line grep.
--
-- Seeding also fixes a plain gap: with empty tables, ANALYZE-mode records report
-- zero rows everywhere, plan shapes that need real data never occur, and the
-- cardinality behaviour in requirements section 9 cannot be exercised at all.
--
-- ANALYZE is run explicitly afterwards.  Without it reltuples stays stale and
-- autovacuum may or may not update it mid-run, which would make plan choice --
-- and therefore the expected output -- nondeterministic.
INSERT INTO zsec_customers (zsec_ssn, zsec_bal, zsec_when, zsec_comp, zsec_kind)
SELECT 'zsecdata-ssn-' || lpad(i::text, 4, '0'),
       (i * 100)::numeric,
       '2020-01-01 00:00:00+00'::timestamptz + (i || ' days')::interval,
       ROW('zsecdata-fld-' || i, 'zsecdata-name-' || i)::zsec_composite,
       (CASE WHEN i % 2 = 0 THEN 'zsec_val_a' ELSE 'zsec_val_b' END)::zsec_enum
  FROM generate_series(1, 20) AS i;

INSERT INTO zsec_orders (zsec_id, zsec_amt)
SELECT i, (i * 7)::numeric FROM generate_series(1, 20) AS i;

ANALYZE zsec_customers;
ANALYZE zsec_orders;

CREATE TABLE zsec_parted (zsec_k int, zsec_ssn text) PARTITION BY RANGE (zsec_k);
CREATE TABLE zsec_parted_p1 PARTITION OF zsec_parted FOR VALUES FROM (0) TO (10);

--
-- The detector.
--
-- Returns one row per distinct fixture identifier found in the EXPLAIN output
-- of the given query.  An empty result means "no leak".  Reporting the
-- identifiers rather than a bare boolean is what makes a failure diagnosable.
--
-- Matching on a substring rather than a whole identifier is intentional: it
-- catches a leak even when the name is embedded in a larger string, such as
-- inside a quoted literal (nextval('zsec_customers_zsec_id_seq')) or inside a
-- deparsed expression.
--
-- Passing an empty option list yields a bare "EXPLAIN <query>", because
-- "EXPLAIN () <query>" is a syntax error.  Once T04 lands, callers pass
-- 'REDACT' (or 'REDACT, VERBOSE', etc.) and the same assertions run inverted.
--
CREATE FUNCTION zsec_leaks(query_text text, explain_opts text)
RETURNS SETOF text
LANGUAGE plpgsql AS
$$
DECLARE
    ln  text;
    buf text := '';
    cmd text;
BEGIN
    IF explain_opts IS NULL OR explain_opts = '' THEN
        cmd := 'EXPLAIN ' || query_text;
    ELSE
        cmd := format('EXPLAIN (%s) %s', explain_opts, query_text);
    END IF;

    FOR ln IN EXECUTE cmd LOOP
        buf := buf || ln || E'\n';
    END LOOP;

    -- Two markers.  "zsec_" tags identifiers; "zsecdata-" tags stored values.
    -- Values need their own alternative because a leaked value is not an
    -- identifier, so an identifier-only pattern is structurally blind to the
    -- entire class of data leaks.
    --
    -- Case-insensitive ('gi'): a marked name or value routed through upper()
    -- arrives as ZSEC_CUSTOMERS and a case-sensitive pattern would read that as
    -- clean.  Harmless while the assertions are positive, exactly wrong once
    -- they invert from T04 onward.  Results are lower-cased so the expected
    -- identifier comparison stays exact.
    -- COLLATE "C" so the identifier order does not depend on the host locale.
    -- It matters even though the markers are pure ASCII: "zsec_ssn" and
    -- "zsecdata-ssn" first differ at "_" against "d", and a linguistic
    -- collation ignores punctuation at the primary level where C does not, so
    -- the two orderings disagree.
    --
    -- The sort is in an outer query rather than on the DISTINCT itself because
    -- ORDER BY on a SELECT DISTINCT has to name a select-list expression, and
    -- "ORDER BY 1 COLLATE \"C\"" does not mean the first column -- it parses as
    -- a collation applied to the integer 1, which fails at run time.
    RETURN QUERY
        SELECT ident
          FROM (SELECT DISTINCT lower(m[1]) AS ident
                  FROM regexp_matches(buf,
                                      '(zsec_[a-z0-9_]*|zsecdata-[a-z0-9-]*)',
                                      'gi') m) d
         ORDER BY ident COLLATE "C";
END
$$;

-- Plan printer for the [C] probes below.  Strips the details that vary between
-- machines so the expected output is stable, while keeping the property names
-- and identifiers that the probes exist to reveal.
CREATE FUNCTION zsec_plan(query_text text, explain_opts text DEFAULT 'COSTS OFF')
RETURNS SETOF text
LANGUAGE plpgsql AS
$$
DECLARE
    ln text;
BEGIN
    FOR ln IN EXECUTE format('EXPLAIN (%s) %s', explain_opts, query_text) LOOP
        CONTINUE WHEN ln ~ '^\s*(Buffers|Memory|Planning|Execution|JIT)';
        ln := regexp_replace(ln, '-?\m\d+\M', 'N', 'g');
        RETURN NEXT ln;
    END LOOP;
END
$$;

--
-- Fixture catalog.  One row per leak path from requirements section 10.2.
-- "opts" records the EXPLAIN options needed to reach the path at all: several
-- properties (Output, Function Call, Table Function Call, Schema) are
-- VERBOSE-only, and a fixture run without VERBOSE would report a false clean.
--
CREATE TABLE zsec_fixtures (fr text, note text, opts text,
                            zsec_expect text, qry text);

-- "zsec_expect" is the identifier the fixture exists to produce.  Counting
-- identifiers is not enough: every fixture reads from zsec_customers.zsec_ssn,
-- so a fixture whose named path contributes nothing still reports a leak and
-- passes.  Four fixtures were doing exactly that before this column existed --
-- the index-name fixture got a Seq Scan, the collation fixture lost its COLLATE
-- to constant folding, the subquery fixture was flattened away, and the
-- composite-assignment fixture never printed a field name.  Naming the target
-- turns that class of mistake red at the moment it is written.
INSERT INTO zsec_fixtures (fr, note, opts, zsec_expect, qry) VALUES
-- FR-10/11/12/13: the baseline names every record carries.
('FR-10', 'relation name',            'COSTS OFF', 'zsec_customers',
 'SELECT * FROM zsec_customers'),
('FR-11', 'schema name (VERBOSE)',    'COSTS OFF, VERBOSE', 'zsec_ns',
 'SELECT * FROM zsec_customers'),
('FR-12', 'column name in Filter',    'COSTS OFF', 'zsec_ssn',
 'SELECT zsec_id FROM zsec_customers WHERE zsec_ssn = ''x'''),
('FR-13', 'user-written alias',       'COSTS OFF', 'zsec_a',
 'SELECT zsec_a.zsec_id FROM zsec_customers zsec_a WHERE zsec_a.zsec_ssn = ''x'''),
-- FR-14/16: object classes with their own emission sites.
('FR-14', 'CTE name',                 'COSTS OFF', 'zsec_cte',
 'WITH zsec_cte AS MATERIALIZED (SELECT zsec_ssn FROM zsec_customers) SELECT * FROM zsec_cte'),
('FR-16', 'arbiter index (ON CONFLICT)', 'COSTS OFF', 'zsec_idx_ssn',
 'INSERT INTO zsec_customers (zsec_ssn) VALUES (''x'') ON CONFLICT (zsec_ssn) DO NOTHING'),
-- NB: the FR-16 "index name" scan fixture is NOT here.  It needs the planner
-- pushed off a sequential scan, which is a GUC, so it lives in its own section
-- below alongside the other GUC-dependent fixtures.
-- FR-18/20/21: names and values inside expressions.
('FR-18', 'user function name',       'COSTS OFF', 'zsec_func',
 'SELECT zsec_id FROM zsec_customers WHERE zsec_func(zsec_ssn)'),
('FR-20', 'user type in cast',        'COSTS OFF', 'zsec_enum',
 'SELECT zsec_id FROM zsec_customers WHERE zsec_kind = ''zsec_val_a''::zsec_enum'),
-- COLLATE on the CONSTANT, not on the Var.  On the Var, eval_const_expressions
-- absorbs it into the operator's inputcollid and no CollateExpr survives to
-- deparse, so the collation name never appears.
('FR-20', 'user collation',           'COSTS OFF', 'zsec_coll',
 'SELECT zsec_id FROM zsec_customers WHERE zsec_ssn < (''x'' COLLATE zsec_coll)'),
('FR-21', 'literal value',            'COSTS OFF', 'zsec_val_secret',
 'SELECT zsec_id FROM zsec_customers WHERE zsec_ssn = ''zsec_val_secret'''),
('FR-21', 'enum literal',             'COSTS OFF', 'zsec_val_b',
 'SELECT zsec_id FROM zsec_customers WHERE zsec_kind = ''zsec_val_b'''),
-- FR-22/FR-23 (query text, parameter values) and FR-17 (the trigger section)
-- are not reachable from plain EXPLAIN: the first two are emitted only by
-- auto_explain, and the third needs ANALYZE plus log_triggers.  They are
-- covered by contrib/auto_explain/t/002_redact.pl instead.
-- FR-46: columns of RTEs that have no relid.  Each is a separate case on
-- purpose -- combined into one query, a single passing path would mask a
-- failing one.
-- OFFSET 0 stops the subquery being flattened into the outer scan; without it
-- the plan is a bare Seq Scan and neither the alias nor the output name exists.
('FR-46', 'subquery output name + alias', 'COSTS OFF', 'zsec_sub',
 'SELECT zsec_sub.zsec_out FROM (SELECT zsec_ssn AS zsec_out FROM zsec_customers OFFSET 0) AS zsec_sub WHERE zsec_sub.zsec_out = ''x'''),
-- NB: the VALUES fixture the requirements doc proposed for FR-46 is NOT here.
-- T01 established that a VALUES RTE's alias and column aliases never reach
-- EXPLAIN output at all; see the negative-control section below.
('FR-46', 'function-scan column alias', 'COSTS OFF, VERBOSE', 'zsec_gc',
 'SELECT * FROM generate_series(1,3) AS zsec_g(zsec_gc) WHERE zsec_gc > 1'),
-- Marked aliases: unmarked ones ("a", "b") would make a leaked join-RTE alias
-- invisible to the detector.
('FR-46', 'join output names',        'COSTS OFF', 'zsec_ja',
 'SELECT * FROM zsec_customers zsec_ja JOIN zsec_orders zsec_jb USING (zsec_id) WHERE zsec_id > 0'),
('FR-46', 'CTE column aliases',       'COSTS OFF', 'zsec_cc',
 'WITH zsec_cte2(zsec_cc) AS MATERIALIZED (SELECT zsec_ssn FROM zsec_customers) SELECT * FROM zsec_cte2 WHERE zsec_cc = ''x'''),
-- FR-90/91: sub-plan labels and window names.
('FR-90', 'Subplan Name carries CTE name', 'COSTS OFF', 'zsec_cte3',
 'WITH zsec_cte3 AS MATERIALIZED (SELECT zsec_ssn FROM zsec_customers) SELECT * FROM zsec_cte3'),
('FR-91', 'window name',              'COSTS OFF', 'zsec_win',
 'SELECT zsec_ssn, rank() OVER zsec_win FROM zsec_customers WINDOW zsec_win AS (PARTITION BY zsec_ssn ORDER BY zsec_bal)'),
-- FR-93/94: composite field names and named-argument labels.
('FR-93', 'composite field select',   'COSTS OFF', 'zsec_fld_ssn',
 'SELECT zsec_id FROM zsec_customers WHERE (zsec_comp).zsec_fld_ssn = ''x'''),
-- Reaches the whole-row branch of get_name_for_var_field(), which resolves the
-- field name through get_rte_attribute_name() -- a different return path from
-- the composite-select case above.  The expected identifier is the same
-- ("zsec_ssn"), so this one leans on plan shape rather than on the name.
('FR-93', 'whole-row field reference', 'COSTS OFF, VERBOSE', 'zsec_ssn',
 'SELECT (zsec_c).zsec_ssn FROM zsec_customers zsec_c'),
-- NB: the "composite field assignment" fixture is NOT here.  T01 could find no
-- shape in which an UPDATE of a composite subfield prints the field name; see
-- the negative-control section.
-- NB: the FR-94 "named argument label" fixture is NOT here either; see the
-- negative-control section.
-- FR-96: JSON path and PASSING labels.
('FR-96', 'JSON_TABLE path labels',   'COSTS OFF, VERBOSE', 'zsec_path',
 'SELECT * FROM JSON_TABLE(''{"a":1,"b":[{"c":2}]}''::jsonb, ''$'' AS zsec_path COLUMNS (zsec_jcol int PATH ''$.a'', NESTED PATH ''$.b[*]'' AS zsec_nest COLUMNS (zsec_jc2 int PATH ''$.c'')))'),
('FR-96', 'JSON_QUERY PASSING label', 'COSTS OFF, VERBOSE', 'zsec_pass',
 'SELECT JSON_QUERY(''{"a":1}''::jsonb, ''$.a'' PASSING 5 AS zsec_pass)'),
-- FR-98: second-path names and raw-datum constants.
('FR-98a', 'sort key COLLATE',        'COSTS OFF', 'zsec_coll',
 'SELECT zsec_ssn FROM zsec_customers ORDER BY zsec_ssn COLLATE zsec_coll'),
-- Only the column name is observable here.  The EXTRACT field label ("year")
-- and the constant (2020) carry no marker and cannot, so this fixture pins the
-- column and nothing else; the raw-datum constant path is asserted on plan text
-- in the probe section instead.
('FR-98d', 'EXTRACT field + value',   'COSTS OFF', 'zsec_when',
 'SELECT zsec_id FROM zsec_customers WHERE EXTRACT(year FROM zsec_when) = 2020'),
-- FR-99: sequence name inside a quoted literal.
('FR-99', 'nextval sequence name',    'COSTS OFF, VERBOSE', 'zsec_customers_zsec_id_seq',
 'INSERT INTO zsec_customers (zsec_ssn) VALUES (''x'')'),
-- FR-13b: RETURNING OLD/NEW aliases.
('FR-13b', 'RETURNING OLD/NEW alias', 'COSTS OFF, VERBOSE', 'zsec_old',
 'UPDATE zsec_customers SET zsec_bal = zsec_bal RETURNING WITH (OLD AS zsec_old, NEW AS zsec_new) zsec_old.zsec_bal, zsec_new.zsec_bal'),
-- FR-10 target-relation variants for DML.
('FR-10', 'UPDATE target',            'COSTS OFF', 'zsec_customers',
 'UPDATE zsec_customers SET zsec_bal = 0'),
('FR-10', 'DELETE target',            'COSTS OFF', 'zsec_customers',
 'DELETE FROM zsec_customers'),
('FR-10', 'MERGE target',             'COSTS OFF', 'zsec_customers',
 'MERGE INTO zsec_customers zsec_mt USING zsec_orders zsec_ms ON zsec_mt.zsec_id = zsec_ms.zsec_id WHEN MATCHED THEN DO NOTHING');

--
-- MARKING DISCIPLINE
--
-- The detector only works if every object in the fixture schema actually
-- carries the marker.  Marking them by hand and eyeballing it is not a
-- guarantee: one unmarked column is a permanent blind spot that no later test
-- would ever report, because the thing it would have caught is invisible to the
-- grep.
--
-- So the convention is enforced rather than trusted.  This query returns any
-- object in the schema whose name is not marked; it must return nothing.
-- Adding an unmarked fixture object is then a test failure at the moment of
-- writing, not a silent hole discovered years later.
--
-- Placed after the LAST object is created.  Run earlier -- as the first draft
-- was, before zsec_fixtures existed -- and anything created afterwards is
-- unchecked by construction, which makes the stated invariant false.
--
-- The pattern allows a leading underscore because PostgreSQL names the array
-- type of "zsec_foo" as "_zsec_foo".
--
SELECT kind, name FROM (
    SELECT 'relation' AS kind, c.relname::text AS name
      FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = 'zsec_ns'
    UNION ALL
    -- Sequences and indexes are excluded, with cause.  A sequence relation has
    -- three fixed internal columns (last_value, log_cnt, is_called) chosen by
    -- PostgreSQL, not by us, and they cannot carry user information.  Index
    -- column names either mirror the underlying table's columns -- already
    -- covered by this same query -- or are generated for expression indexes.
    -- Everything else with columns is in scope.
    SELECT 'column', a.attname::text
      FROM pg_attribute a
      JOIN pg_class c ON c.oid = a.attrelid
      JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = 'zsec_ns' AND a.attnum > 0 AND NOT a.attisdropped
       AND c.relkind NOT IN ('S', 'i')
    UNION ALL
    SELECT 'function', p.proname::text
      FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
     WHERE n.nspname = 'zsec_ns'
    UNION ALL
    SELECT 'type', t.typname::text
      FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
     WHERE n.nspname = 'zsec_ns'
    UNION ALL
    SELECT 'collation', cl.collname::text
      FROM pg_collation cl JOIN pg_namespace n ON n.oid = cl.collnamespace
     WHERE n.nspname = 'zsec_ns'
    UNION ALL
    SELECT 'constraint', con.conname::text
      FROM pg_constraint con JOIN pg_namespace n ON n.oid = con.connamespace
     WHERE n.nspname = 'zsec_ns'
    UNION ALL
    -- Function argument names are the one catalog the fixture set depends on
    -- that the first draft of this query missed: FR-94's named-argument label
    -- was marked by hand and enforced by nothing.
    SELECT 'argument name', unnest(p.proargnames)::text
      FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
     WHERE n.nspname = 'zsec_ns' AND p.proargnames IS NOT NULL
    UNION ALL
    SELECT 'enum label', e.enumlabel::text
      FROM pg_enum e
      JOIN pg_type t ON t.oid = e.enumtypid
      JOIN pg_namespace n ON n.oid = t.typnamespace
     WHERE n.nspname = 'zsec_ns'
) obj
 WHERE name !~ '^_?zsec_'
 -- COLLATE "C" on every text sort in this file: the suite runs under whatever
 -- locale the build host has, and a linguistic collation orders these rows
 -- differently from C.  pg_upgrade's test harness initialises its cluster with a
 -- different locale than "make check" does, so without this the same tree
 -- produces two different expected outputs.
 ORDER BY kind COLLATE "C", name COLLATE "C";

-- Same idea for the seeded data: every stored value must carry the marker, or a
-- leaked value would be invisible to the detector.  Must return nothing.
SELECT 'unmarked value' AS problem, v
  FROM (
    SELECT zsec_ssn AS v FROM zsec_customers
    UNION ALL SELECT (zsec_comp).zsec_fld_ssn FROM zsec_customers
    UNION ALL SELECT (zsec_comp).zsec_fld_name FROM zsec_customers
    UNION ALL SELECT zsec_kind::text FROM zsec_customers
  ) vals
 WHERE v IS NOT NULL AND v !~ '^zsec'
 ORDER BY v COLLATE "C";

--
-- POSITIVE CONTROL
--
-- Every fixture must leak the identifier it names.  "FAIL" means either the
-- detector is broken or the fixture does not reach the path it claims to -- both
-- are T01 failures, and both must be resolved before any later task relies on
-- this harness.  The found list is printed on failure so the cause is visible
-- without re-running anything.
--
SELECT f.fr,
       f.note,
       CASE WHEN f.zsec_expect = ANY (g.found) THEN 'ok'
            ELSE 'FAIL: want ' || f.zsec_expect || ', got '
                 || coalesce(array_to_string(g.found, ' '), '(nothing)')
       END AS verdict
  FROM zsec_fixtures f
  CROSS JOIN LATERAL (SELECT array_agg(l ORDER BY l COLLATE "C") AS found
                        FROM zsec_leaks(f.qry, f.opts) AS l) g
 ORDER BY f.fr COLLATE "C", f.note COLLATE "C", f.qry COLLATE "C";

--
-- GUC-dependent fixtures.  These cannot share the table-driven run above
-- without changing every other fixture's plan, so each sets what it needs and
-- resets it.
--

-- FR-16, index name on a scan.  With 20 rows the planner never chooses the
-- index, so the index-name emission site is not reached at all and the fixture
-- would have reported success having never printed an index name.
SET enable_seqscan = off;
SET enable_bitmapscan = off;

SELECT 'FR-16' AS fr, 'index name (scan)' AS note,
       CASE WHEN 'zsec_idx_ssn' = ANY (array_agg(l)) THEN 'ok'
            ELSE 'FAIL: want zsec_idx_ssn, got '
                 || coalesce(array_to_string(array_agg(l), ' '), '(nothing)')
       END AS verdict
  FROM zsec_leaks('SELECT zsec_ssn FROM zsec_customers WHERE zsec_ssn = ''x''',
                  'COSTS OFF') AS l;

RESET enable_bitmapscan;
RESET enable_seqscan;

--
-- FORMAT COVERAGE
--
-- Standing criterion 2 requires every fixture to be clean in all four formats,
-- but every fixture above runs text only.  The property that makes the
-- single-format run defensible is that the markers survive each format's
-- escaping unchanged -- "zsec_" and "zsecdata-" contain no character that
-- escape_json, the XML escaper or escape_yaml touches, and no format wraps long
-- lines, so an identifier is never split across a boundary.  That is load-
-- bearing and nothing pinned it, so pin it here: the same query must yield the
-- same identifier set in all four formats.
--
SELECT format_name,
       CASE WHEN found = (SELECT array_agg(l ORDER BY l COLLATE "C")
                            FROM zsec_leaks('SELECT zsec_a.zsec_id FROM zsec_customers zsec_a WHERE zsec_a.zsec_ssn = ''zsec_val_secret''',
                                            'COSTS OFF') AS l)
            THEN 'same as text'
            ELSE 'DIFFERS: ' || array_to_string(found, ' ') END AS verdict
  FROM (VALUES ('text'), ('json'), ('xml'), ('yaml')) AS fmt(format_name),
       LATERAL (SELECT array_agg(l ORDER BY l COLLATE "C") AS found
                  FROM zsec_leaks('SELECT zsec_a.zsec_id FROM zsec_customers zsec_a WHERE zsec_a.zsec_ssn = ''zsec_val_secret''',
                                  'COSTS OFF, FORMAT ' || fmt.format_name) AS l) g
 ORDER BY format_name;

--
-- NEGATIVE CONTROL, established by T01: an UPDATE of a composite subfield never
-- prints the field name.  The requirements proposed this as an FR-93 fixture;
-- no shape reaches a field-name emission site through an assignment -- not with
-- a column source, not with RETURNING.  The field name reaches output through a
-- READ, which the "composite field select" and "whole-row field reference"
-- fixtures already cover.
--
-- Retained as an assertion rather than deleted, so that if a future version
-- starts printing the target field name it fails here instead of shipping
-- silently.
--
SELECT count(*) AS assignment_must_not_print_field_name
  FROM zsec_leaks('UPDATE zsec_customers SET zsec_comp.zsec_fld_ssn = ''x''',
                  'COSTS OFF, VERBOSE') AS l
 WHERE l = 'zsec_fld_ssn';

--
-- NEGATIVE CONTROL, established by T01: a named-argument label never reaches a
-- plan.  The parser resolves named notation to positional order and discards the
-- NamedArgExpr wrapper, so "zsec_func(zsec_arg => zsec_ssn)" deparses as
-- "zsec_func(zsec_ssn)".  Verified with arguments given OUT OF ORDER, which is
-- the case that forces the parser to reorder and so had the best chance of
-- preserving the labels -- it does not.
--
-- ruleutils.c's T_NamedArgExpr branch therefore serves raw parse trees, such as
-- a stored default expression printed by pg_get_expr(), not plan trees.  FR-94
-- is a guard for a path EXPLAIN cannot currently reach, like FR-98c.
--
-- Pinned rather than dropped, so that if named arguments ever start surviving
-- into plans this fails instead of shipping silently.
--
SELECT count(*) AS named_arg_label_must_not_reach_a_plan
  FROM zsec_leaks('SELECT zsec_id FROM zsec_customers WHERE zsec_func(zsec_arg => zsec_ssn)',
                  'COSTS OFF') AS l
 WHERE l = 'zsec_arg';

--
-- FR-92 fixtures need a non-default constraint_exclusion, so they cannot share
-- the table-driven run above without changing every other fixture's plan.
--
SET constraint_exclusion = on;

SELECT 'FR-92' AS fr, 'Replaces: relation name' AS note,
       count(l) > 0 AS leaks
  FROM zsec_leaks('SELECT * FROM zsec_excluded WHERE zsec_k < 0', 'COSTS OFF') AS l;

SELECT 'FR-92' AS fr, 'Replaces: join aliases' AS note,
       count(l) > 0 AS leaks
  FROM zsec_leaks('SELECT * FROM zsec_excluded zsec_ja JOIN zsec_excluded zsec_jb USING (zsec_k) WHERE zsec_ja.zsec_k < 0',
                    'COSTS OFF') AS l;

RESET constraint_exclusion;

--
-- Detector self-check: it must not report a leak where there is none, or the
-- "clean" assertions in every later task are worthless.
--
SELECT count(*) AS must_be_zero
  FROM zsec_leaks('SELECT 1', 'COSTS OFF');

-- "timestamp with time zone" contains "zone".  This is the false positive that
-- a bare /z[a-z_]+/ detector would report, and the reason the marker prefix is
-- four characters long.
SELECT count(*) AS must_be_zero_time_zone_is_not_a_leak
  FROM zsec_leaks('SELECT now() AT TIME ZONE ''UTC''', 'COSTS OFF');

--
-- NEGATIVE CONTROL, established by T01: a VALUES range-table entry discloses
-- nothing, because its user-written alias and column aliases do not survive
-- into the plan.  EXPLAIN prints the planner's internal "*VALUES*" name and
-- column1..columnN instead.  This holds in every shape tried: bare, wrapped in
-- an un-flattenable subquery, LATERAL, and INSERT ... VALUES.
--
-- Pinned as a test rather than deleted: if a future version starts propagating
-- the user's alias into the plan, this assertion fails and a new leak path gets
-- noticed instead of shipping silently.
--
SELECT count(*) AS values_alias_must_not_leak
  FROM zsec_leaks('SELECT * FROM (VALUES (1,2),(3,4)) AS zsec_v(zsec_v1, zsec_v2) WHERE zsec_v1 > 0',
                    'COSTS OFF, VERBOSE');

-- Column aliases written on a VALUES clause DO reach output when the VALUES is
-- wrapped in a subquery that survives flattening -- but as the *subquery's*
-- column names, which the "subquery output name + alias" fixture already
-- covers.  Recorded so the distinction is documented.
SELECT count(l) > 0 AS values_aliases_leak_via_enclosing_subquery
  FROM zsec_leaks('SELECT * FROM (SELECT * FROM (VALUES (1,2),(3,4)) AS zsec_v(zsec_v1,zsec_v2) OFFSET 0) zsec_w WHERE zsec_w.zsec_v1 > 0',
                    'COSTS OFF, VERBOSE') AS l;

--
-- Stateful fixture: WHERE CURRENT OF needs a live cursor, so it cannot live in
-- the table-driven catalog above.
--
BEGIN;
DECLARE zsec_cur CURSOR FOR SELECT * FROM zsec_customers FOR UPDATE;
SELECT count(l) > 0 AS cursor_name_leaks
  FROM zsec_leaks('UPDATE zsec_customers SET zsec_bal = 0 WHERE CURRENT OF zsec_cur',
                    'COSTS OFF') AS l;
ROLLBACK;

--
-- [C] PROBES
--
-- Three entries in the requirements catalog were marked "needs confirmation":
-- the query shape that reaches them was derived by reading the code, not by
-- running it.  T01 resolves them.  These probes print the plan so the answer
-- is recorded in the expected output rather than in someone's memory.
--

-- [C] FR-92: does a childless Result node with a non-empty relids set actually
-- appear, and does it emit a "Replaces" property naming the relation?
-- show_result_replacement_info() returns early when plan.lefttree is non-NULL,
-- so a gating Result (One-Time Filter) is not enough; the scan or the aggregate
-- itself has to have been replaced.
-- ANSWER: confirmed.  Three distinct forms, and they differ in whether a name
-- follows the replacement type -- all three must be covered by T15.
SET constraint_exclusion = on;

SELECT 'FR-92 probe: scan replacement -> Replaces carries a RELATION NAME' AS probe;
SELECT * FROM zsec_plan('SELECT * FROM zsec_excluded WHERE zsec_k < 0');

SELECT 'FR-92 probe: join replacement -> Replaces carries ALIASES' AS probe;
SELECT * FROM zsec_plan('SELECT * FROM zsec_excluded zsec_ja JOIN zsec_excluded zsec_jb USING (zsec_k) WHERE zsec_ja.zsec_k < 0');

RESET constraint_exclusion;

SELECT 'FR-92 probe: MinMax replacement -> Replaces carries NO name' AS probe;
SELECT * FROM zsec_plan('SELECT min(zsec_bal) FROM zsec_customers');

-- Contrast: a contradictory qual on a column with no supporting CHECK
-- constraint is NOT proven empty, and constraint_exclusion defaults to
-- "partition" (which only applies to partitions and inheritance children), so
-- neither of those alone produces a replacement.  Recorded so the two
-- preconditions are documented rather than rediscovered.
SELECT 'FR-92 probe: contradictory qual, no constraint, default GUC (control)' AS probe;
SELECT * FROM zsec_plan('SELECT * FROM zsec_customers WHERE zsec_ssn IS NULL AND zsec_ssn IS NOT NULL');

-- [C] FR-13a: which statement drives refname through the alias/fallback path
-- rather than through get_rel_name()?
--
-- ANSWER: the SELECT, not the INSERT.  Scanning a partitioned parent emits
-- BOTH names on one line -- the partition child as the object name and the
-- parent as the reference name -- so a single scan node discloses two
-- identifiers and T15 has to redact both.  The INSERT takes the ordinary
-- nominal-relation path and discloses only the parent.
SELECT 'FR-13a probe: INSERT into partitioned parent (ordinary path)' AS probe;
SELECT * FROM zsec_plan('INSERT INTO zsec_parted VALUES (1, ''x'')');

SELECT 'FR-13a probe: SELECT from partitioned parent (child + parent, one line)' AS probe;
SELECT * FROM zsec_plan('SELECT * FROM zsec_parted WHERE zsec_k = 1');

-- [C] FR-90 second seed: the subquery-alias seed at allpaths.c reaches
-- subroot->plan_name, but a subquery in FROM becomes a SubqueryScan (or is
-- flattened away entirely), not a SubPlan.  Does the alias surface as a
-- Subplan Name at all?
--
-- ANSWER: no.  Flattened, the alias vanishes completely; un-flattened, it
-- appears as a Subquery Scan alias -- which is FR-13's territory, not FR-90's.
-- No "Subplan Name" is produced either way.  The requirements catalog entry for
-- this seed should be narrowed to say the seed reaches subroot->plan_name but
-- not EXPLAIN output.  FR-90's CTE seed (above) remains confirmed.
SELECT 'FR-90 probe: subquery alias seed, flattened -> alias vanishes' AS probe;
SELECT * FROM zsec_plan('SELECT * FROM (SELECT count(*) FROM zsec_customers) AS zsec_alias');

SELECT 'FR-90 probe: subquery alias seed, un-flattenable -> Subquery Scan alias, no Subplan Name' AS probe;
SELECT * FROM zsec_plan('SELECT * FROM (SELECT zsec_ssn, count(*) FROM zsec_customers GROUP BY zsec_ssn OFFSET 0) AS zsec_alias2 WHERE zsec_alias2.zsec_ssn = ''x''');

--
-- Cleanup.  The fixture schema is dropped so this file leaves no state behind
-- for other regression tests running in the same database.
--
RESET search_path;
DROP SCHEMA zsec_ns CASCADE;
